<?

global $_c;
$_c->CHROMIUM_EXEC_RELOAD = 1;
$_c->CHROMIUM_EXEC_GOBACK = 2;
$_c->CHROMIUM_EXEC_CANGOBACK = 3;
$_c->CHROMIUM_EXEC_GOFORWARD = 4;
$_c->CHROMIUM_EXEC_CANGOFORWARD = 5;
$_c->CHROMIUM_EXEC_SHOWDEVTOOLS = 6;
$_c->CHROMIUM_EXEC_HIDEDEVTOOLS = 7;
$_c->CHROMIUM_EXEC_HIDEPOPUP = 8;
$_c->CHROMIUM_EXEC_SETFOCUS = 9;
$_c->CHROMIUM_EXEC_RELOADIGNORECACHE = 10;
$_c->CHROMIUM_EXEC_STOPLOAD = 11;
$_c->CHROMIUM_EXEC_SETFOCUSEVENT = 12;
$_c->CHROMIUM_EXEC_SETEVENTKEY = 13;
$_c->CHROMIUM_EXEC_MOUSECLICKEVENT = 14;
$_c->CHROMIUM_EXEC_LOAD = 15;
$_c->CHROMIUM_EXEC_SCROLLBY = 16;
$_c->CHROMIUM_EXEC_CLEARHISTORY = 17;

$_c->CHROMIUM_EXEC_UNDO = 22;
$_c->CHROMIUM_EXEC_REDO = 23;
$_c->CHROMIUM_EXEC_CUT  = 24;
$_c->CHROMIUM_EXEC_COPY = 25;
$_c->CHROMIUM_EXEC_PASTE= 26;
$_c->CHROMIUM_EXEC_DEL  = 27;
$_c->CHROMIUM_EXEC_SELECTALL = 28;
$_c->CHROMIUM_EXEC_PRINT = 29;
$_c->CHROMIUM_EXEC_VIEWSOURCE = 30;
$_c->CHROMIUM_EXEC_LOADURL = 31;
$_c->CHROMIUM_EXEC_LOADSTRING = 32;
$_c->CHROMIUM_EXEC_LOADFILE = 33;
$_c->CHROMIUM_EXEC_EXECUTEJS = 34;
$_c->CHROMIUM_EXEC_ZOOM = 35;
$_c->CHROMIUM_EXEC_DEFENCODING = 37;
$_c->CHROMIUM_EXEC_DEFCSSPATH = 36;
$_c->CHROMIUM_EXEC_SOURCE = 38;
$_c->CHROMIUM_EXEC_ADDRESS = 39;